apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: policy-decision-point-repo
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./regression-test-deploy/src/main/resources/apps/policy-decision-point
      sourceRef:
        kind: GitRepository
        name: policy-decision-point-repo
        namespace: default
      interval: 5m
      reconcileStrategy: Revision
      valuesFiles:
        - values.yaml
        - values-dev.yaml