apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: policy-decision-point
  namespace: default
spec:
  interval: 5m0s
  ref:
    branch: main
  secretRef:
    name: ssh-auth
  url: ssh://git@github.com/carter-cundiff/aissemble-regression-test
  ignore: |
    # exclude all
    /*
    # include singular charts directory
    !regression-test-deploy/src/main/resources/apps/policy-decision-point/ 